RBAC_OU_MODEL_SETTING = 'RBAC_OU_MODEL'
RBAC_ROLE_MODEL_SETTING = 'RBAC_ROLE_MODEL'
RBAC_ROLE_PARENTING_MODEL_SETTING = 'RBAC_ROLE_PARENTING_MODEL'
RBAC_PERMISSION_MODEL_SETTING = 'RBAC_PERMISSION_MODEL'
