#!/bin/sh

if [ "$(whoami)" != "authentic" ]; then
    if which sudo; then
      if sudo -v -u authentic; then
        sudo -u authentic authentic2-ctl "$@"
        exit $?
      fi
      echo "You must run this script with authentic user"
      exit 1
    fi
fi

if [ -f /etc/authentic2/authentic.conf ]; then
    . /etc/authentic2/authentic.conf
fi

/usr/lib/authentic2/manage.py "$@"
